<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #222; }
    h1 { font-size: 16px; margin: 0 0 2px; }
    .meta { color: #666; font-size: 9px; margin-bottom: 10px; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th, td { border: 1px solid #ccc; padding: 4px 6px; text-align: left; }
    th { background: #f0f0f0; font-weight: bold; }
    .summary-table { width: auto; margin-bottom: 12px; }
    .summary-table td:first-child { font-weight: bold; }
    .note { color: #b45309; font-size: 9px; margin-top: 8px; }
    .report-letterhead { position: relative; margin-bottom: 12px; padding-bottom: 8px; border-bottom: 2px solid #333; }
    .report-letterhead-watermark { position: absolute; top: 0; left: 0; right: 0; bottom: 0; z-index: 0; text-align: center; opacity: 0.15; }
    .report-letterhead-watermark img { max-width: 55%; max-height: 100%; object-fit: contain; }
    .report-letterhead-content { position: relative; z-index: 1; }
    .report-letterhead-logo-row { width: 100%; border-collapse: collapse; margin-bottom: 6px; }
    .report-letterhead-logo-row td { border: none; padding: 0; vertical-align: middle; }
    .report-letterhead-logo-row-bg { position: absolute; top: 0; left: 0; right: 0; z-index: 0; margin-bottom: 0; }
    .report-letterhead-logo-row-bg-bottom { top: auto; bottom: 0; }
    .report-letterhead-logo-cell-left { width: 33.33%; text-align: left; }
    .report-letterhead-logo-cell-center { width: 33.33%; text-align: center; }
    .report-letterhead-logo-cell-right { width: 33.33%; text-align: right; }
    .report-letterhead-logo-row img { height: 48px; width: auto; }
    .report-letterhead-body p { margin: 2px 0; }
</style>
</head>
<body>
    {!! $headerHtml ?? '' !!}
    <h1>{{ $title }}</h1>
    <div class="meta">
        Generated by {{ $generatedBy }} on {{ $generatedAt }}
        @if (count($filters))
            &mdash;
            @foreach ($filters as $key => $value)
                {{ ucfirst(str_replace('_', ' ', $key)) }}: {{ $value }}@if (! $loop->last), @endif
            @endforeach
        @endif
    </div>

    @if ($summary)
        <table class="summary-table">
            @foreach ($summary as $item)
                <tr><td>{{ $item['label'] }}</td><td>{{ $item['value'] }}</td></tr>
            @endforeach
        </table>
    @endif

    <table>
        <thead>
            <tr>
                @foreach ($columns as $column)
                    <th>{{ $column['label'] }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    @foreach ($columns as $column)
                        <td>{{ $row[$column['key']] ?? '' }}</td>
                    @endforeach
                </tr>
            @empty
                <tr><td colspan="{{ count($columns) }}">No records found.</td></tr>
            @endforelse
        </tbody>
    </table>

    @if ($truncated)
        <div class="note">Showing first {{ count($rows) }} of {{ $totalCount }} records. Export as CSV for the full data set.</div>
    @endif
</body>
</html>
