<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $now = now();

        DB::transaction(function () use ($now): void {
            $contentHtml = <<<'HTML'
<h2 style="margin:0;font-size:18px;">{{barangay_name}}</h2>
<p style="margin:2px 0;">{{barangay_address}}, {{barangay_city_municipality}}, {{barangay_province}}</p>
<p style="margin:2px 0;font-size:9px;color:#555;">{{barangay_contact_number}} &middot; {{barangay_email}}</p>
HTML;

            DB::table('document_templates')->updateOrInsert(
                ['code' => 'REPORT-DEFAULT'],
                [
                    'name' => 'Default Report Letterhead',
                    'description' => 'Default letterhead header rendered on every Reports module PDF export.',
                    'content_html' => $contentHtml,
                    'variables' => json_encode([
                        ['key' => 'barangay_name', 'label' => 'Barangay Name'],
                        ['key' => 'barangay_address', 'label' => 'Barangay Address'],
                        ['key' => 'barangay_city_municipality', 'label' => 'City / Municipality'],
                        ['key' => 'barangay_province', 'label' => 'Province'],
                        ['key' => 'barangay_contact_number', 'label' => 'Contact Number'],
                        ['key' => 'barangay_email', 'label' => 'Email'],
                        ['key' => 'punong_barangay_name', 'label' => 'Punong Barangay Name'],
                        ['key' => 'report_title', 'label' => 'Report Title'],
                        ['key' => 'generated_by', 'label' => 'Generated By'],
                        ['key' => 'generated_at', 'label' => 'Generated At'],
                        ['key' => 'today', 'label' => 'Current Date'],
                    ]),
                    'logo_placements' => json_encode([]),
                    'document_type' => 'report',
                    'is_default' => true,
                    'paper_size' => 'a4',
                    'status' => 'active',
                    'created_at' => $now,
                    'updated_at' => $now,
                ]
            );
        });
    }

    public function down(): void
    {
        DB::table('document_templates')->where('code', 'REPORT-DEFAULT')->delete();
    }
};
